name: google_maps_flutter_example
description: Demonstrates how to use the google_maps_flutter plugin.
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  cupertino_icons: ^0.1.0
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.1
  google_maps_flutter:
    git:
      path: google_maps_flutter
      ref: from-file-fix
      url: https://github.com/KWRI/google_maps_flutter.git
  google_maps_flutter_android:
    git:
      path: google_maps_flutter_android
      ref: from-file-fix
      url: https://github.com/KWRI/google_maps_flutter.git
  google_maps_flutter_platform_interface:
    git:
      path: google_maps_flutter_platform_interface
      ref: from-file-fix
      url: https://github.com/KWRI/google_maps_flutter.git

dev_dependencies:
  espresso: ^0.2.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
