name: google_maps_flutter_web_integration_tests
publish_to: none

# Tests require flutter beta or greater to run.
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter_platform_interface:
    git:
      path: google_maps_flutter_platform_interface
      ref: from-file-fix
      url: https://github.com/KWRI/google_maps_flutter.git
  google_maps_flutter_web:
    git:
      path: google_maps_flutter_web
      ref: from-file-fix
      url: https://github.com/KWRI/google_maps_flutter.git

dev_dependencies:
  build_runner: ^2.1.1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  google_maps: ^6.1.0
  google_maps_flutter:
    git:
      path: google_maps_flutter
      ref: from-file-fix
      url: https://github.com/KWRI/google_maps_flutter.git
  http: ^0.13.0
  integration_test:
    sdk: flutter
  mockito: ^5.3.2
